apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-ui
spec:
  replicas: 4
  revisionHistoryLimit: 3
  strategy:
    canary: # A new field that used to provide configurable options for a Canary strategy
      steps:
        - setWeight: 20
        - pause: {}
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: guestbook-ui
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
